### ISSUE TITLE
Add configuration options

### ISSUE THREAD

**Issue by yassineS** [LPM-HMS/Cosmos2#1]
This needs to be added in the same fashion as COSMOS 1.0. There's no evident way to select the DB configuration, the out/scratch folders or the DRM.

**Comment by yassineS** [comment]
What about the MySQL or Postgresql? How to point to the data base and the username and password.

**Comment by egafni** [comment]
@yassineS Good point, I updated the docs:
http://cosmos-wfm.readthedocs.org/en/latest/workflows/initializing.html
