### ISSUE TITLE
Documentation offline ?

### ISSUE THREAD

**Issue by kevintc** [LPM-HMS/Cosmos2#30]
Hello,

Links seem to be broken for the following ressources :
http://cosmos.hms.harvard.edu/COSMOS-2.0/
http://cosmos-wfm.readthedocs.org/en/latest/

There is still a documentation there (and I guess it's for 1.0) but without styling :
http://cosmos.hms.harvard.edu/documentation/index.html

Is there any up to date documentation available ?

**Comment by egafni** [comment]
Thanks for catching that, I updated the repo name but forgot to update the link in the README: http://cosmos.hms.harvard.edu/COSMOS2/

**Comment by nudomarinero** [comment]
Hello,
The links to the documentation (http://lpm-hms.github.io/COSMOS2/ or http://cosmos.hms.harvard.edu/COSMOS2/) seem to be broken again.

**Comment by egafni** [comment]
Thanks, it should have been http://cosmos.hms.harvard.edu/Cosmos2/
