### ISSUE TITLE
question about project with multiple workflow

### ISSUE THREAD

**Issue by aurelBZH** [LPM-HMS/COSMOS2#36]
hello
In your examples you show a way to setup a project with multiple workflow but what is the best to link 2 workflow? I want my second workflow to work on the result file of my first workflow 

 thanks for your help

**Comment by egafni** [comment]
There's a few ways to do that:
ex1 = cosmos.start()
t1 = ex1.add_task()
ex1.run()

ex2 = cosmos.start()
ex2.add_task(load_input(in_file=t1.output_files[0]))
ex2.run()

Or:
def workflow1_recipe(ex):
  return ex.add_task(func1)

def workflow2_recipe(ex, parents):
  return ex.add_task(func2, parents)

ex = cosmos.start()
wf1_out = workflow1_recipe(ex)
workflow2_recipe(ex, wf1_out)
ex.run()
