### ISSUE TITLE
question about the setup of cosmos on computer cluster

### ISSUE THREAD

**Issue by aurelBZH** [LPM-HMS/COSMOS2#37]
Hello,
I have tried to run my workflow on a computer cluster with pbs scheduler and torque resource manager. I have installed drmaa and cosmos but I'm unable configure cosmos for this drm. Is it possible ? What is the best way?
Aurélien

**Comment by egafni** [comment]
The only thing you should have to do is specify your own get_submit_args function when you run Cosmos.start().  See the default function's code for an example.  This function passes DRM-specific arguments.
