### ISSUE TITLE
execution of python code after the end of a cosmos task

### ISSUE THREAD

**Issue by aurelBZH** [LPM-HMS/COSMOS2#50]
hello,
Is there a way to execute python code after the end of a cosmos task? I have try some tricks like taskname.finished but it doesn't seem  to work.

thanks for your help 

edited : miss somethings

**Comment by egafni** [comment]
You could create a dependent Task which returns None, or use a signal:

```
@signal_task_status_change.connect
def task_status_changed(task):
  if task.status in [TaskStatus.failed, TaskStatus.successful]:
    ..

```

https://github.com/LPM-HMS/COSMOS2/blob/master/cosmos/models/Task.py#L50
