### ISSUE TITLE
Extract task results within workflow

### ISSUE THREAD

**Issue by kmhernan** [LPM-HMS/COSMOS2#57]
I have a situation where I am trying to scatter/gather; however, I am unable to know how many chunks I will be generating until I run a particular task (I would know the maximum number of chunks the user requested, but there are several reasons that the number of chunks actually produced is less than this number). I would then gather all the files (chunks) produced by this task by listing the files in a particular directory. All of my downstream tasks depend on the number of chunks produced here. That includes the non-task logic that would occur (e.g., looping over n-chunks to make n-scatter jobs). So that chunk number is kind of like a "promise" from the task. I don't really see how I can do this in your framework; however, I do feel like it is not an uncommon situation for complex workflows. Any suggestions?

**Comment by egafni** [comment]
You can run workflow.run() once to complete the Task(s) you need to get the information necessary to create the rest of the DAG.  Then continue modifying the DAG as usual via workflow.add_task(), and then call workflow.run() again to run the rest of the jobs.

I've gotten this question a couple of times so will add to the FAQ
