### ISSUE TITLE
All Licenses Mentioned

### ISSUE THREAD

**Issue by doctormo** [LPM-HMS/COSMOS2#59]
The project seems to be licensed under a number of conflicting licenses depending on what source of information is used:

 * setup.py says the project is under an MIT License
 * LICENSE says it's a GPLv3 License
 * Website (http://cosmos.hms.harvard.edu/) in the FAQ says the project is Apache 2.0 Licensed.

These should probably all say the same thing.

**Comment by egafni** [comment]
The original verison, was released under a different license than Cosmos2 (this repository, which is MIT licensed).

Will work on clarifying, thanks.

@yassineS are you guys done with Cosmos1?  I would like to merge the repositories and remove most references to it aside from a legacy link.

**Comment by egafni** [comment]
Everything is updated
