### ISSUE TITLE
1.0.15, cosmos/graph/draw.py: 'DiGraph' object has no attribute 'layout'

### ISSUE THREAD

**Issue by al7000** [LPM-HMS/Cosmos2#6]
Hi Erik,

I am running Cosmos under Apache (WSGI). Trying to display the TaskGraph of the ex1.py generates an internal server error. It does not seem wsgi-related. Here is the httpd error_log: 
File "/var/www/cosmos-wfm-1.0.15/cosmos/graph/draw.py", line 60, in taskgraph_to_image
[Fri Apr 24 17:02:04.119419 2015] [:error] [pid 23091] [remote 10.38.34.24:208]     taskgraph.layout(prog="dot")
[Fri Apr 24 17:02:04.119436 2015] [:error] [pid 23091] [remote 10.38.34.24:208] AttributeError: 'DiGraph' object has no attribute 'layout'
Thank you for your help.
Best,
A.

**Comment by egafni** [comment]
Thanks for the bug report!
Fixed by 34842faad3dab381c33f52bc86e612c43b3756e0
