### ISSUE TITLE
cosmos: error: too few arguments error even after setting 

### ISSUE THREAD

**Issue by man4ish** [LPM-HMS/COSMOS2#82]
I could install cosmos using following steps mentioned in 

https://github.com/LPM-HMS/GenomeKey/wiki/test-new-docs

but i get following error while running

 
(cosmos) manish $ cosmos 
usage: cosmos [-h] {runweb,shell,run} ...
cosmos: error: too few arguments

I am working on local pc (without using any cluster). I created manually with default information ~/.virtualenvs/cosmos/lib/python2.7/site-packages/cosmos/default_config.ini but still same issue. 

Even though i installed cosmos using pip still i get same error. May i know how can i fix this issue?

**Comment by egafni** [comment]
you must use `cosmos -h` to get the full help message
