### ISSUE TITLE
How to change `_default_task_log_output_dir`

### ISSUE THREAD

**Issue by btrspg** [LPM-HMS/COSMOS2#85]
Hi there,

I want to change the `log` dir, but in `default_task_log_output_dir`,maybe it  always be the Running dir.
Can some one help me?

Thanks !

**Comment by egafni** [comment]
def f(task):
   return os.path.abspath(opj('/anything/you/want', task.stage.name, str(task.uid)))

Workflow.run(log_out_dir_func=f)

**Comment by btrspg** [comment]
Hi,
Sorry about not describe my question clearly.
In 

```python
return os.path.abspath(opj('/anything/you/want', task.stage.name, str(task.uid)))
```

I want to use a optional `PATH`  instead of a `immobilization` PATH . 

Maybe I wonder how can I give a parameter to the function,like

```
def f(task,optional_path='/anything/you/want'):
return os.path.abspath(opj(optional_path, task.stage.name, str(task.uid)))

## used it 


```
### ?
Workflow.run(log_out_dir_func=f)
```
