### ISSUE TITLE
How to change the `log` dir

### ISSUE THREAD

**Issue by btrspg** [LPM-HMS/COSMOS2#88]
former issue is #85 

Hi, @egafni
Sorry about not describe my question clearly.
In

return os.path.abspath(opj('/anything/you/want', task.stage.name, str(task.uid)))
I want to use a optional PATH instead of a immobilization PATH . (Because I just want give record log of a batch data in the results of batch data direction)

Maybe I wonder how can I give a parameter to the function,like

def f(task,optional_path='/anything/you/want'):
    return os.path.abspath(opj(optional_path, task.stage.name, str(task.uid)))

## used it 

?
Workflow.run(log_out_dir_func=f)

**Comment by egafni** [comment]
Sorry, I don't think I understand

**Comment by btrspg** [comment]
In #85 you told me

```python
def f(task):
    return os.path.abspath(opj('/anything/you/want', task.stage.name, str(task.uid)))
```
to use my own path to put the log,but the `/anything/you/want` was  an immobilization `PATH`. And I need a mobilization `PATH` to put the log in.

If I ran

```python
Workflow.run(log_out_dir_func=f)
```

my log were just in `/anything/you/want` , what should I done if I want put my logs in another `PATH` ,like 'rna-seq-batch1-date' direction. And when I run my pipeline another time , I put my logs in another like 'rna-seq-batch2-date2'.

Sorry about my poor English.

**Comment by egafni** [comment]
Instead of trying this, i recommend this:
```
mkdir /path/to/rna-seq-batch1-date
cd  /path/to/rna-seq-batch1-date
python /path/to/cosmos_script.py

etc.
```

**Comment by btrspg** [comment]
Thank you very much. 

I have tried something else like:

```python
def pipeline(args):
    # ...
    # some code
    #...
    cosmos = Cosmos('sqlite:///%s/sqlite.db' % args.sqlite,
                    default_max_attempts=args.max_attempts,
                    )
    cosmos.initdb()
    # def the change_log_dir in the function of pipeline
    def change_log_dir(task,dir=args.log):
        return os.path.abspath(os.path.join(dir, task.stage.name, str(task.uid)))

    workflow = cosmos.start('rna-seq-analysis-pipeline', restart=False, skip_confirm=True,
                            primary_log_path='{}/workflow.log'.format(args.outdir))

    recipe(workflow, cfg, paras_list)

    workflow.make_output_dirs()
    workflow.run(max_cores=args.cores,log_out_dir_func=change_log_dir)
```

I found this could solve my problem. But maybe it would lead some bugs I have not  foresee. If I meet  I would change to your recommendation.

Thanks for your patience.
